name: Push GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/joelverhagen/data-az-retail-prices.git
          cd pages
          npm ci
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
