# Periodically checks the Azure Retail Price API for new prices
# Inspired by https://simonwillison.net/2020/Oct/9/git-scraping/

name: Update data

on:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Update snapshot
        shell: pwsh
        run: |
          ./snapshot.ps1 -Buckets 16

      - shell: pwsh
        run: dotnet run --project ./src/AzureRetailPrices.Tool --configuration Release -- load-database

      - name: Commit and push if data has changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601=seconds)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
